export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_PREFERENCES = 'SET_USER_PREFERENCES';
export const SET_USER_COORDS = 'SET_USER_COORDS';
export const SET_LOCATION = 'SET_LOCATION';

export const SET_DEVICES = 'SET_DEVICES';

export const SET_GARAGE_COORDS = 'SET_GARAGE_COORDS';
export const SET_GARAGE_DOORS = 'SET_GARAGE_DOORS';
export const UPDATE_GARAGE_DOORS = 'UPDATE_GARAGE_DOORS';

export const SET_LIGHTS = 'SET_LIGHTS';
export const SET_SCENES = 'SET_SCENES';
export const ADD_SCENE = 'ADD_SCENE';
export const DELETE_SCENE = 'DELETE_SCENE';

export const SET_TEMP_DATA = 'SET_TEMP_DATA';
export const SET_FORECAST_DATA = 'SET_FORECAST_DATA';
export const SET_EXTENDED_FORECAST = 'SET_EXTENDED_FORECAST';

export const SET_SUMP_DATA = 'SET_SUMP_DATA';

export const SET_SCHEDULED_TASK = 'SET_SCHEDULED_TASK';
export const ADD_SCHEDULED_TASK = 'ADD_SCHEDULED_TASK';
export const DELETE_SCHEDULED_TASK = 'DELETE_SCHEDULED_TASK';
